image:
  registry: docker.io
  repository: bitnamilegacy/keycloak
  tag: 26.3.3-debian-12-r0

auth:
  adminUser: admin
  adminPassword: "CHANGE_ME_KEYCLOAK_ADMIN"

production: true
proxy: edge
proxyHeaders: xforwarded
useHelmHooks: false

extraEnvVars:
  - name: KC_METRICS_ENABLED
    value: "true"
  - name: KC_HEALTH_ENABLED
    value: "true"

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.homelab.local
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
  extraTls:
    - hosts:
        - keycloak.homelab.local
      secretName: keycloak-tls

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

postgresql:
  enabled: true
  image:
    registry: public.ecr.aws
    repository: bitnami/postgresql
    tag: "18.3.0-debian-12-r7"
  volumePermissions:
    image:
      registry: public.ecr.aws
      repository: bitnami/os-shell
      tag: latest
  metrics:
    image:
      registry: public.ecr.aws
      repository: bitnami/postgres-exporter
      tag: latest
  auth:
    postgresPassword: "KeycloakPG2024!"
    password: "l7B4tSX5QB"
    username: bn_keycloak
    database: keycloak
  primary:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

keycloakConfigCli:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/keycloak-config-cli
    tag: 6.4.0-debian-12-r11
  configuration:
    homelab-realm.json: |
      {
        "realm": "homelab",
        "displayName": "HomeLab",
        "displayNameHtml": "<div style='text-align:center'><img src='https://homelab.local/en/wp-content/uploads/2024/08/emage_logo_site-Phone-300x155.png' alt='HomeLab' style='max-width:200px;margin:10px auto'/><br/><span style='color:#373A6F;font-size:14px'>Future-Proof Your Skills and Level Up Your Career</span></div>",
        "enabled": true,
        "sslRequired": "external",
        "registrationAllowed": false,
        "loginWithEmailAllowed": true,
        "resetPasswordAllowed": true,
        "bruteForceProtected": true,
        "clients": [
          {
            "clientId": "argocd",
            "name": "ArgoCD",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "argocd-keycloak-secret-2024",
            "redirectUris": [
              "https://argocd.homelab.local/auth/callback",
              "https://argocd.homelab.local:31753/auth/callback"
            ],
            "webOrigins": [
              "https://argocd.homelab.local",
              "https://argocd.homelab.local:31753"
            ],
            "standardFlowEnabled": true,
            "directAccessGrantsEnabled": true,
            "protocol": "openid-connect",
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "full.path": "false",
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "grafana",
            "name": "Grafana",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "grafana-keycloak-secret-2024",
            "redirectUris": [
              "https://grafana.homelab.local/login/generic_oauth"
            ],
            "webOrigins": [
              "https://grafana.homelab.local"
            ],
            "standardFlowEnabled": true,
            "directAccessGrantsEnabled": true,
            "protocol": "openid-connect",
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "full.path": "false",
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "harbor",
            "name": "Harbor",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "harbor-keycloak-secret-2024",
            "redirectUris": [
              "https://harbor.homelab.local/c/oidc/callback"
            ],
            "webOrigins": [
              "https://harbor.homelab.local"
            ],
            "standardFlowEnabled": true,
            "directAccessGrantsEnabled": true,
            "protocol": "openid-connect",
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "full.path": "false",
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "gitlab",
            "name": "GitLab",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "CHANGE_ME_GITLAB_OIDC",
            "redirectUris": [
              "https://gitlab.homelab.local/users/auth/openid_connect/callback"
            ],
            "webOrigins": [
              "https://gitlab.homelab.local"
            ],
            "standardFlowEnabled": true,
            "directAccessGrantsEnabled": true,
            "protocol": "openid-connect",
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "full.path": "false",
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "mattermost",
            "name": "Mattermost",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "CHANGE_ME_MATTERMOST_OIDC",
            "redirectUris": [
              "https://mattermost.homelab.local/signup/gitlab/complete"
            ],
            "webOrigins": [
              "https://mattermost.homelab.local"
            ],
            "standardFlowEnabled": true,
            "directAccessGrantsEnabled": true,
            "protocol": "openid-connect",
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "full.path": "false",
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "jupyterhub",
            "name": "JupyterHub",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "jupyterhub-keycloak-secret-2024",
            "redirectUris": [
              "https://jupyter.homelab.local/hub/oauth_callback"
            ],
            "webOrigins": [
              "https://jupyter.homelab.local"
            ],
            "standardFlowEnabled": true,
            "directAccessGrantsEnabled": true,
            "protocol": "openid-connect",
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "full.path": "false",
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          }
        ],
        "groups": [
          {
            "name": "admins",
            "path": "/admins"
          }
        ],
        "users": [
          {
            "username": "user",
            "enabled": true,
            "email": "user@homelab.local",
            "firstName": "Kenna",
            "lastName": "Ofoegbu",
            "emailVerified": true,
            "credentials": [
              {
                "type": "password",
                "value": "CHANGE_ME_USER_PASSWORD",
                "temporary": false
              }
            ],
            "groups": [
              "/admins"
            ]
          }
        ]
      }
