replicaCount: 1

manager:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus

  prometheusRule:
    enabled: false

# Enable auto-instrumentation for Java, Python, Node.js, Go, .NET
admissionWebhooks:
  certManager:
    enabled: true
    issuerRef:
      kind: ClusterIssuer
      name: homelab-ca-issuer
